server:
  port: 8080

# Services
external-services:
  auth:
    url: http://pump-auth-service:8080

  social:
    url: http://pump-social-service:8080

# Logging
logging:
  level:
    com.johnmartin.coaching: INFO

spring:
  jpa:
    hibernate:
      ddl-auto: update
